# Generated by Django 2.1.5 on 2019-01-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='aber_only',
            field=models.BooleanField(default=False),
        ),
    ]
