# Generated by Django 2.0.9 on 2018-12-14 13:59

import abercompsoc.events.models
from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('date', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('max_attendees', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('time', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='UserEventAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(choices=[(abercompsoc.events.models.UserEventAssociationType('NoAssociation'), 'NoAssociation'), (abercompsoc.events.models.UserEventAssociationType('Interested'), 'Interested'), (abercompsoc.events.models.UserEventAssociationType('WantingToAttend'), 'WantingToAttend'), (abercompsoc.events.models.UserEventAssociationType('Waiting'), 'Waiting'), (abercompsoc.events.models.UserEventAssociationType('Attending'), 'Attending')], default='NA', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(through='events.UserEventAssociation', to=settings.AUTH_USER_MODEL),
        ),
    ]
